ALTER TABLE company
MODIFY created_on DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
MODIFY modified_on DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE user
MODIFY created_on DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
MODIFY modified_on DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE client
MODIFY created_on DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
MODIFY modified_on DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE bearer_token
MODIFY created_on DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
MODIFY modified_on DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
