CREATE TABLE role (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    modified_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE user_role (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    fk_user_id INT NOT NULL,
    fk_role_id INT NOT NULL,
    created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    modified_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_user_id_user FOREIGN KEY (fk_user_id) REFERENCES user(id) ,
    CONSTRAINT fk_role_id_role FOREIGN KEY (fk_role_id) REFERENCES role(id)
);
